apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  k8s-app: metallb
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/metallb.yaml
  - metal-lb-layer2-config.yaml
